/**
 * Renovyte Product Database
 * Used for dynamic catalog rendering and product detail population.
 */

window.RenovyteProducts = [
    // --- SERVICE & MAINTENANCE ---
    {
        id: "service-oil-1",
        name: "Royal Purple 5W-30 Synthetic Oil (5L)",
        category: "Service & Maintenance",
        subcategory: "Engine Oils",
        price: "KES 8,500",
        image: "assets/images/products/service-parts/service-1.webp",
        images: [
            "assets/images/products/service-parts/service-1.webp",
            "assets/images/products/service-parts/service-2.webp",
            "assets/images/products/service-parts/service-3.webp"
        ],
        description: "Increases horsepower and torque, saves fuels and reduces heat, wear, and emissions.",
        make: "UNIVERSAL",
        model: "Universal",
        rating: 4.9
    },
    {
        id: "service-filter-1",
        name: "K&N Performance Oil Filter",
        category: "Service & Maintenance",
        subcategory: "Oil Filters",
        price: "KES 2,400",
        image: "assets/images/products/service-parts/service-2.webp",
        description: "High flow rates, exceptional filtration, and durable construction.",
        make: "NISSAN",
        model: "Navara",
        year: "2018",
        engine: "2500cc",
        rating: 4.8
    },
    {
        id: "service-plug-1",
        name: "NGK Iridium IX Spark Plugs (Set of 4)",
        category: "Service & Maintenance",
        subcategory: "Spark plugs",
        price: "KES 3,200",
        image: "assets/images/products/service-parts/service-3.webp",
        description: "Designed specifically for the performance enthusiast. Iridium IX offers extreme ignitability.",
        make: "TOYOTA",
        model: "Corolla",
        year: "2021",
        engine: "1800cc",
        rating: 4.9
    },

    // --- TIRE AND WHEELS ---
    {
        id: "tyre-michelin-1",
        name: "Michelin Pilot Sport 4S (245/40R18)",
        category: "Tire and Wheels",
        subcategory: "Tire and Wheels",
        price: "KES 35,000",
        image: "assets/images/products/tyres-wheels/tyres-1.webp",
        description: "Genuine Passion. Exceptional Drive. High performance summer tyre.",
        make: "UNIVERSAL",
        model: "Universal",
        year: "All Years",
        engine: "Universal",
        rating: 5.0
    },
    {
        id: "wheel-rays-1",
        name: "Volk Racing TE37 (18x9.5)",
        category: "Tire and Wheels",
        subcategory: "Rims",
        price: "KES 85,000",
        image: "assets/images/products/tyres-wheels/tyres-2.webp",
        description: "The benchmark of forged sports wheels. Extremely lightweight and strong.",
        make: "SUBARU",
        model: "Impreza",
        year: "2020",
        engine: "2000cc",
        rating: 5.0
    },
    {
        id: "tyre-service-1",
        name: "Premium Tyre Installation & Balancing Service",
        category: "Tire and Wheels",
        subcategory: "Tire and Wheels",
        price: "KES 1,500",
        image: "assets/images/products/tyres-wheels/tyres-3.webp",
        description: "Professional mounting and high-speed precision balancing using state-of-the-art machinery.",
        make: "UNIVERSAL",
        model: "Universal",
        rating: 4.8
    },

    // --- BRAKING SYSTEM ---
    {
        id: "brake-pads-1",
        name: "Brembo Front Performance Brake Pads",
        category: "Braking System",
        subcategory: "Braking System",
        price: "KES 12,500",
        image: "assets/images/products/braking-system/braking-1.webp",
        description: "Brembo ceramic brake pads are engineered for superior stopping power.",
        make: "TOYOTA",
        model: "Land Cruiser",
        year: "2022",
        engine: "3300cc",
        rating: 4.9
    },
    {
        id: "brake-discs-1",
        name: "EBC Slotted Brake Rotors (Pair)",
        category: "Braking System",
        subcategory: "Braking System",
        price: "KES 28,000",
        image: "assets/images/products/braking-system/braking-2.webp",
        description: "Wide aperture slots draw cool air into the braking contact area.",
        make: "BMW",
        model: "3 Series",
        year: "2021",
        engine: "2000cc",
        rating: 4.8
    },
    {
        id: "brake-brembo-kit-1",
        name: "Brembo High-Performance Brake System Kit",
        category: "Braking System",
        subcategory: "Braking System",
        price: "KES 185,000",
        image: "assets/images/products/braking-system/braking-3.webp",
        description: "Complete professional-grade braking conversion kit with oversized rotors and 6-piston calipers.",
        make: "UNIVERSAL",
        model: "High Performance",
        rating: 5.0
    },

    // --- CAR LIGHTING ---
    {
        id: "light-led-1",
        name: "Philips X-tremeUltinon LED Headlights",
        category: "Car Lighting",
        subcategory: "LED Bulbs",
        price: "KES 18,000",
        image: "assets/images/products/lighting/lighting-1.webp",
        description: "Get 200% brighter light for superior visibility and style.",
        make: "UNIVERSAL",
        model: "Universal",
        rating: 4.8
    },
    {
        id: "light-bar-1",
        name: "Rigid Industries 20-inch Light Bar",
        category: "Car Lighting",
        subcategory: "DRLs (Daytime Running lights)",
        price: "KES 45,000",
        image: "assets/images/products/lighting/lighting-2.webp",
        description: "The most popular light bar on the market. Indestructible lighting power.",
        make: "FORD",
        model: "Ranger",
        year: "2021",
        engine: "3200cc",
        rating: 4.9
    },
    {
        id: "light-angel-eye-1",
        name: "BMW M-Style Angel Eye Headlight Set",
        category: "Car Lighting",
        subcategory: "Headlights",
        price: "KES 52,000",
        image: "assets/images/products/lighting/lighting-3.webp",
        description: "Premium LED Angel Eye headlights with aggressive M-styling and crystal clear white output.",
        make: "BMW",
        model: "3 Series / 5 Series",
        year: "2018",
        rating: 4.9
    },

    // --- CAR ACCESSORIES ---
    {
        id: "acc-perfume-1",
        name: "Air Spencer CS-X3 Squash Scent",
        category: "Car Accessories",
        subcategory: "Car Polish & Sprays",
        price: "KES 1,200",
        image: "assets/images/products/exterior-accessories/acc-1.webp",
        description: "The famous Japanese JDM air freshener with a clean squash scent.",
        make: "UNIVERSAL",
        model: "Universal",
        rating: 4.9
    },
    {
        id: "acc-mats-1",
        name: "WeatherTech Floor Liners (Front Pair)",
        category: "Car Accessories",
        subcategory: "Floor Mats",
        price: "KES 18,500",
        image: "assets/images/products/exterior-accessories/acc-2.webp",
        description: "Laser measured for a perfect fit and maximum floor protection.",
        make: "TOYOTA",
        model: "Prado",
        year: "2019",
        engine: "3000cc",
        rating: 4.8
    },

    // --- BODY PARTS ---
    {
        id: "body-bonnet-1",
        name: "Premium Luxury Steel Bonnet",
        category: "Body Parts",
        subcategory: "Bonnets",
        price: "KES 55,000",
        image: "assets/images/products/body-parts/bonnet-1.png",
        description: "High-quality steel bonnet engineered for a perfect fit and superior durability.",
        make: "MERCEDES",
        model: "S-Class",
        year: "2023",
        rating: 4.9
    },
    {
        id: "body-bonnet-2",
        name: "Performance Carbon Fiber Vented Hood",
        category: "Body Parts",
        subcategory: "Hoods",
        price: "KES 120,000",
        image: "assets/images/products/body-parts/bonnet-2.png",
        description: "Ultra-lightweight carbon fiber hood with aerodynamic cooling vents.",
        make: "BMW",
        model: "M4",
        year: "2024",
        rating: 5.0
    },
    {
        id: "body-boot-1",
        name: "Replacement Rear Tailgate Assembly",
        category: "Body Parts",
        subcategory: "Boot/ Tail Gates",
        price: "KES 42,000",
        image: "assets/images/products/body-parts/boot-1.png",
        description: "OEM quality rear boot gate with integrated glass and electronics wiring.",
        make: "TOYOTA",
        model: "RAV4",
        year: "2022",
        rating: 4.8
    },
    {
        id: "body-boot-2",
        name: "Luxury Sedan Trunk Lid",
        category: "Body Parts",
        subcategory: "Boot/ Tail Gates",
        price: "KES 38,000",
        image: "assets/images/products/body-parts/boot-2.png",
        description: "Precision-crafted trunk lid featuring a sleek, aerodynamic design.",
        make: "AUDI",
        model: "A6",
        year: "2023",
        rating: 4.7
    },
    {
        id: "body-bumper-1",
        name: "M-Performance Front Bumper Kit",
        category: "Body Parts",
        subcategory: "Bumpers",
        price: "KES 45,000",
        image: "assets/images/products/body-parts/body-1.webp",
        images: [
            "assets/images/products/body-parts/body-1.webp",
            "assets/images/products/body-parts/bumper-2.png",
            "assets/images/products/body-parts/bumper-3.png"
        ],
        description: "Transform your vehicle's appearance with this aggressive m-style bumper.",
        make: "BMW",
        model: "5 Series",
        year: "2022",
        engine: "3000cc",
        rating: 4.7
    },
    {
        id: "body-bumper-2",
        name: "Premium Front Guard Bumper",
        category: "Body Parts",
        subcategory: "Bumpers",
        price: "KES 48,000",
        image: "assets/images/products/body-parts/bumper-2.png",
        description: "Robust front bumper designed for maximum protection and elegant aesthetics.",
        make: "LAND ROVER",
        model: "Sport",
        year: "2023",
        rating: 4.9
    },
    {
        id: "body-bumper-3",
        name: "Sport Rear Diffuser Bumper",
        category: "Body Parts",
        subcategory: "Bumpers",
        price: "KES 52,000",
        image: "assets/images/products/body-parts/bumper-3.png",
        description: "Aerodynamic rear bumper with integrated carbon fiber diffuser.",
        make: "PORSCHE",
        model: "911",
        year: "2024",
        rating: 5.0
    },
    {
        id: "body-skirt-1",
        name: "Luxury Side Skirting Set",
        category: "Body Parts",
        subcategory: "Bumper side skirting",
        price: "KES 28,000",
        image: "assets/images/products/body-parts/skirt-1.png",
        description: "Sleek side skirts that enhance the vehicle's low-profile aesthetic.",
        make: "MERCEDES",
        model: "C-Class",
        year: "2023",
        rating: 4.8
    },
    {
        id: "body-skirt-2",
        name: "Carbon Fiber Aerodynamic Skirts",
        category: "Body Parts",
        subcategory: "Bumper side skirting",
        price: "KES 65,000",
        image: "assets/images/products/body-parts/skirt-2.png",
        description: "Performance-oriented carbon fiber side skirts for high-speed stability.",
        make: "LAMBORGHINI",
        model: "Huracan",
        year: "2024",
        rating: 5.0
    },
    {
        id: "body-slides-1",
        name: "Bumper Retaining Bracket Set",
        category: "Body Parts",
        subcategory: "Bumper slides",
        price: "KES 4,500",
        image: "assets/images/products/body-parts/slides-1.png",
        description: "High-precision bumper slides for secure mounting and alignment.",
        make: "UNIVERSAL",
        model: "Universal",
        rating: 4.6
    },
    {
        id: "body-slides-2",
        name: "Front Bumper Mounting Clips",
        category: "Body Parts",
        subcategory: "Body Parts",
        price: "KES 3,200",
        image: "assets/images/products/body-parts/slides-2.png",
        description: "OEM equivalent bumper mounting clips and slides for easy installation.",
        make: "UNIVERSAL",
        model: "Universal",
        rating: 4.5
    },
    {
        id: "body-horn-1",
        name: "Dual-Tone Chrome Performance Horns",
        category: "Body Parts",
        subcategory: "Car Horns",
        price: "KES 6,500",
        image: "assets/images/products/body-parts/horn-1.png",
        description: "Powerful dual-tone horns with a premium chrome finish for maximum clarity.",
        make: "UNIVERSAL",
        model: "Universal",
        rating: 4.9
    },
    {
        id: "body-horn-2",
        name: "Compact Electric Stealth Horn",
        category: "Body Parts",
        subcategory: "Body Parts",
        price: "KES 3,800",
        image: "assets/images/products/body-parts/horn-2.png",
        description: "Discreet and powerful electric horn with a weather-resistant black finish.",
        make: "UNIVERSAL",
        model: "Universal",
        rating: 4.7
    },
    {
        id: "body-door-motor-1",
        name: "Power Window Regulator & Motor",
        category: "Body Parts",
        subcategory: "Door Motors",
        price: "KES 14,500",
        image: "assets/images/products/body-parts/door-motor-1.png",
        description: "Reliable power window motor assembly for smooth and quiet operation.",
        make: "TOYOTA",
        model: "Prado",
        year: "2020",
        rating: 4.8
    },
    {
        id: "body-door-motor-2",
        name: "Central Locking Actuator Motor",
        category: "Body Parts",
        subcategory: "Body Parts",
        price: "KES 8,500",
        image: "assets/images/products/body-parts/door-motor-2.png",
        description: "High-torque actuator motor for secure central locking performance.",
        make: "VOLKSWAGEN",
        model: "Golf",
        year: "2022",
        rating: 4.7
    },
    {
        id: "body-mirror-1",
        name: "Carbon Fiber Wing Mirror Covers",
        category: "Body Parts",
        subcategory: "Side Mirrors",
        price: "KES 7,500",
        image: "assets/images/products/body-parts/body-2.webp",
        description: "Gloss black or real carbon fiber replacement mirror covers.",
        make: "MERCEDES",
        model: "C-Class",
        year: "2020",
        engine: "2000cc",
        rating: 4.5
    },
    {
        id: "body-drive-shaft-1",
        name: "Replacement Front Drive Shaft",
        category: "Body Parts",
        subcategory: "Drive shafts",
        price: "KES 18,500",
        image: "assets/images/products/body-parts/drive-shaft-1.png",
        description: "Heavy-duty drive shaft assembly for smooth power transmission.",
        make: "TOYOTA",
        model: "Hilux",
        year: "2021",
        rating: 4.8
    },
    {
        id: "body-drive-shaft-2",
        name: "Performance 4x4 Drive Shaft",
        category: "Body Parts",
        subcategory: "Drive shafts",
        price: "KES 24,000",
        image: "assets/images/products/body-parts/drive-shaft-2.png",
        description: "Enhanced durability drive shaft designed for off-road performance.",
        make: "FORD",
        model: "Ranger",
        year: "2023",
        rating: 4.9
    },
    {
        id: "body-wing-1",
        name: "Luxury Front Wing / Fender",
        category: "Body Parts",
        subcategory: "Front Wings",
        price: "KES 22,000",
        image: "assets/images/products/body-parts/wing-1.png",
        description: "Precision-molded front fender with perfect alignment points.",
        make: "LEXUS",
        model: "RX350",
        year: "2022",
        rating: 4.7
    },
    {
        id: "body-wing-2",
        name: "Wide-Body Sport Fender",
        category: "Body Parts",
        subcategory: "Front Wings",
        price: "KES 35,000",
        image: "assets/images/products/body-parts/wing-2.png",
        description: "Custom wide-body fender for an aggressive stance and better tire clearance.",
        make: "BMW",
        model: "M3",
        year: "2023",
        rating: 5.0
    },
    {
        id: "body-grille-1",
        name: "Executive Chrome Front Grille",
        category: "Body Parts",
        subcategory: "Grilles",
        price: "KES 15,500",
        image: "assets/images/products/body-parts/grille-1.png",
        description: "Premium chrome-finished grille for a sophisticated front-end look.",
        make: "TOYOTA",
        model: "Land Cruiser",
        year: "2021",
        rating: 4.9
    },
    {
        id: "body-grille-2",
        name: "Matte Black Honeycomb Grille",
        category: "Body Parts",
        subcategory: "Grilles",
        price: "KES 12,000",
        image: "assets/images/products/body-parts/grille-2.png",
        description: "Sporty matte black grille with a honeycombed mesh design.",
        make: "VOLKSWAGEN",
        model: "Golf R",
        year: "2022",
        rating: 4.8
    },
    {
        id: "body-hood-1",
        name: "Performance Vented Hood",
        category: "Body Parts",
        subcategory: "Hoods",
        price: "KES 85,000",
        image: "assets/images/products/body-parts/hood-1.png",
        description: "Aggressive vented hood for improved engine cooling and aesthetics.",
        make: "SUBARU",
        model: "WRX STI",
        year: "2021",
        rating: 4.9
    },
    {
        id: "body-hood-2",
        name: "Lightweight Aluminum Hood",
        category: "Body Parts",
        subcategory: "Hoods",
        price: "KES 65,000",
        image: "assets/images/products/body-parts/hood-2.png",
        description: "OEM-style lightweight aluminum hood for weight reduction.",
        make: "UNIVERSAL",
        model: "Model 3",
        year: "2023",
        rating: 4.8
    },
    {
        id: "body-ignition-1",
        name: "Premium Ignition Lock Cylinder",
        category: "Body Parts",
        subcategory: "Ignition Switches",
        price: "KES 8,500",
        image: "assets/images/products/body-parts/ignition-1.png",
        description: "Secure ignition lock cylinder with two encoded master keys.",
        make: "UNIVERSAL",
        model: "Universal",
        rating: 4.7
    },
    {
        id: "body-ignition-2",
        name: "Illuminated Push Start Module",
        category: "Body Parts",
        subcategory: "Ignition Switches",
        price: "KES 12,000",
        image: "assets/images/products/body-parts/ignition-2.png",
        description: "Modern push-to-start button module with LED illumination.",
        make: "MERCEDES",
        model: "E-Class",
        year: "2022",
        rating: 5.0
    },
    {
        id: "body-radiator-1",
        name: "High-Flow Aluminum Radiator",
        category: "Body Parts",
        subcategory: "Radiators",
        price: "KES 24,000",
        image: "assets/images/products/body-parts/radiator-1.png",
        description: "Dual-core aluminum radiator for maximum cooling efficiency.",
        make: "UNIVERSAL",
        model: "Universal",
        rating: 4.9
    },
    {
        id: "body-radiator-2",
        name: "Complete Radiator & Fan Assembly",
        category: "Body Parts",
        subcategory: "Radiators",
        price: "KES 35,000",
        image: "assets/images/products/body-parts/radiator-2.png",
        description: "Integrated radiator and dual cooling fan unit for easy installation.",
        make: "TOYOTA",
        model: "Corolla",
        year: "2020",
        rating: 4.8
    },
    {
        id: "body-rear-cut-1",
        name: "Luxury Sedan Rear Body Cut",
        category: "Body Parts",
        subcategory: "Rear Cuts",
        price: "KES 150,000",
        image: "assets/images/products/body-parts/rear-cut-1.png",
        description: "Complete rear body section including quarter panels and chassis points.",
        make: "BMW",
        model: "7 Series",
        year: "2021",
        rating: 4.9
    },
    {
        id: "body-rear-cut-2",
        name: "SUV Rear Chassis Tail Cut",
        category: "Body Parts",
        subcategory: "Rear Cuts",
        price: "KES 120,000",
        image: "assets/images/products/body-parts/rear-cut-2.png",
        description: "Pristine rear tail cut for major collision repair or restoration.",
        make: "TOYOTA",
        model: "Land Cruiser",
        year: "2019",
        rating: 4.8
    },
    {
        id: "body-rear-wing-1",
        name: "Carbon Fiber Trunk Spoiler",
        category: "Body Parts",
        subcategory: "Rear Wings",
        price: "KES 28,000",
        image: "assets/images/products/body-parts/rear-wing-1.png",
        description: "Lightweight carbon fiber spoiler for improved aerodynamics and style.",
        make: "BMW",
        model: "3 Series",
        year: "2022",
        rating: 5.0
    },
    {
        id: "body-rear-wing-2",
        name: "GT Performance Wing",
        category: "Body Parts",
        subcategory: "Rear Wings",
        price: "KES 45,000",
        image: "assets/images/products/body-parts/rear-wing-2.png",
        description: "Adjustable high-downforce GT wing for track-day performance.",
        make: "PORSCHE",
        model: "Cayman",
        year: "2023",
        rating: 4.9
    },
    {
        id: "body-roof-rack-1",
        name: "Aluminum Aero Roof Racks",
        category: "Body Parts",
        subcategory: "Roof Racks",
        price: "KES 18,500",
        image: "assets/images/products/body-parts/roof-rack-1.png",
        description: "Universal aluminum crossbars with aerodynamic profile and locking system.",
        make: "UNIVERSAL",
        model: "Universal",
        rating: 4.7
    },
    {
        id: "body-widebody-1",
        name: "Exotic Performance Wide-Body Conversion",
        category: "Body Parts",
        subcategory: "Body Kit",
        price: "KES 350,000",
        image: "assets/images/products/body-parts/body-3.webp",
        description: "Full exotic wide-body kit featuring aero-optimized panels and aggressive styling.",
        make: "FERRARI",
        model: "488 / F8",
        year: "2019-2023",
        rating: 5.0
    },

    // --- ENGINE & COMPONENTS ---
    {
        id: "engine-pistons-1",
        name: "Mahle Forged PowerPak Piston Set",
        category: "Engine & Components",
        subcategory: "Cylinder Heads",
        price: "KES 95,000",
        image: "assets/images/products/engine-components/engine-1.webp",
        description: "High-strength forged aluminum pistons designed for extreme boost and high RPM.",
        make: "TOYOTA",
        model: "Supra (2JZ/B58)",
        rating: 5.0
    },
    {
        id: "engine-cams-1",
        name: "Brian Crower Stage 2 Sport Camshafts",
        category: "Engine & Components",
        subcategory: "Camshaft Sensors",
        price: "KES 82,000",
        image: "assets/images/products/engine-components/engine-1.webp",
        description: "Plug-and-play camshafts providing significant gains in mid-range torque and top-end power.",
        make: "NISSAN",
        model: "Silvia/Skyline",
        rating: 4.9
    },
    {
        id: "engine-ecu-1",
        name: "Haltech Elite 2500 Standalone ECU",
        category: "Engine & Components",
        subcategory: "ECU computers",
        price: "KES 245,000",
        image: "assets/images/products/accessories/android-radio-1.png",
        description: "World-class engine management system with drive-by-wire and dual-channel knock control.",
        make: "UNIVERSAL",
        model: "Performance Tuned",
        rating: 5.0
    },
    {
        id: "engine-injectors-1",
        name: "Bosch Motorsport 1000cc Fuel Injectors",
        category: "Engine & Components",
        subcategory: "Fuel Pumps",
        price: "KES 65,000",
        image: "assets/images/products/service-parts/service-2.webp",
        description: "Set of 6 high-impedance fuel injectors with exceptional spray atomization.",
        make: "UNIVERSAL",
        model: "High Flow",
        rating: 4.9
    },
    {
        id: "engine-studs-1",
        name: "ARP Pro Series Head Stud Kit",
        category: "Engine & Components",
        subcategory: "Cylinder Heads",
        price: "KES 28,000",
        image: "assets/images/products/body-parts/steering-rack-1.png",
        description: "Ultra-heavy-duty fasteners to prevent cylinder head lifting under high boost.",
        make: "MITSUBISHI",
        model: "Evolution X",
        rating: 5.0
    },
    {
        id: "engine-intake-1",
        name: "Skunk2 Ultra Series Intake Manifold",
        category: "Engine & Components",
        subcategory: "Throttle Body",
        price: "KES 78,000",
        image: "assets/images/products/engine-components/engine-1.webp",
        description: "Designed for maximum volume and high-velocity airflow for turbocharged builds.",
        make: "HONDA",
        model: "Civic Type R",
        rating: 4.8
    },
    {
        id: "engine-radiator-1",
        name: "Mishimoto Performance Aluminum Radiator",
        category: "Engine & Components",
        subcategory: "Radiators",
        price: "KES 42,000",
        image: "assets/images/products/body-parts/radiator-1.png",
        description: "Full aluminum construction providing 30% more efficient cooling than stock.",
        make: "SUBARU",
        model: "WRX STI",
        rating: 4.9
    },
    {
        id: "engine-turbo-1",
        name: "Precision Gen2 6266 Ball Bearing Turbocharger",
        category: "Engine & Components",
        subcategory: "Engine & Components",
        price: "KES 145,000",
        image: "assets/images/products/engine-components/engine-1.webp",
        description: "The Precision Gen2 6266 CEA turbocharger is a powerhouse of performance.",
        make: "UNIVERSAL",
        model: "Universal",
        rating: 4.8
    },
    {
        id: "engine-belt-1",
        name: "Gates Racing Timing Belt",
        category: "Engine & Components",
        subcategory: "Service Parts",
        price: "KES 8,500",
        image: "assets/images/products/engine-components/engine-1.webp",
        description: "Incredibly strong, extremely heat resistant timing belt for racing.",
        make: "MITSUBISHI",
        model: "Lancer Evolution",
        year: "2015",
        engine: "2000cc",
        rating: 4.7
    },

    // --- SUSPENSION & BEARINGS ---
    {
        id: "suspension-coilovers-1",
        name: "Tein Flex Z Coilovers",
        category: "Suspension & Bearings",
        subcategory: "Suspension Bushes",
        price: "KES 115,000",
        image: "assets/images/products/suspension-steering/suspension-1.webp",
        description: "Full-length ride height adjustment feature with twin-tube system.",
        make: "TOYOTA",
        model: "Supra",
        year: "2021",
        engine: "3000cc",
        rating: 5.0
    },
    {
        id: "suspension-shocks-1",
        name: "KYB Excel-G Shock Absorbers (Rear)",
        category: "Suspension & Bearings",
        subcategory: "Shock Absorbers",
        price: "KES 8,500",
        image: "assets/images/products/suspension-steering/suspension-2.webp",
        description: "Restore your vehicle's original ride and handling capabilities.",
        make: "NISSAN",
        model: "X-Trail",
        year: "2020",
        engine: "2000cc",
        rating: 4.6
    },

    // --- SUSPENSION & BEARINGS ---
    {
        id: "suspension-bilstein-1",
        name: "Bilstein B8 Performance Plus Shocks",
        category: "Suspension & Bearings",
        subcategory: "Shock Absorbers",
        price: "KES 115,000",
        image: "assets/images/products/suspension-steering/suspension-2.webp",
        description: "Gas-pressure shock absorbers designed to work with lowering springs for superior handling.",
        make: "BMW",
        model: "M3/M4 (F80)",
        rating: 5.0
    },
    {
        id: "suspension-kw-1",
        name: "KW Variant 3 Coilover System",
        category: "Suspension & Bearings",
        subcategory: "Suspension Bushes",
        price: "KES 285,000",
        image: "assets/images/products/suspension-steering/suspension-1.webp",
        description: "State-of-the-art motorsports technology for individual bump and rebound adjustment.",
        make: "UNIVERSAL",
        model: "911 (991)",
        rating: 5.0
    },
    {
        id: "suspension-eibach-1",
        name: "Eibach Pro-Kit Lowering Springs",
        category: "Suspension & Bearings",
        subcategory: "Coil Springs",
        price: "KES 38,000",
        image: "assets/images/products/suspension-steering/suspension-1.webp",
        description: "Lowers your car's center of gravity for improved cornering and an aggressive look.",
        make: "VOLKSWAGEN",
        model: "Golf GTI",
        rating: 4.8
    },
    {
        id: "suspension-whiteline-1",
        name: "Whiteline Front & Rear Sway Bar Kit",
        category: "Suspension & Bearings",
        subcategory: "Stabilizer Links",
        price: "KES 52,000",
        image: "assets/images/products/suspension-steering/suspension-3.webp",
        description: "Adjustable anti-roll bars to eliminate body roll and perfect your chassis balance.",
        make: "SUBARU",
        model: "Forester/BRZ",
        rating: 4.9
    },
    {
        id: "suspension-moog-1",
        name: "Moog Problem Solver Ball Joint Set",
        category: "Suspension & Bearings",
        subcategory: "Ball Joints",
        price: "KES 12,000",
        image: "assets/images/products/suspension-steering/suspension-2.webp",
        description: "Reinforced greaseable ball joints for durable, precise steering response.",
        make: "UNIVERSAL",
        model: "High Duty",
        rating: 4.7
    },
    {
        id: "suspension-bcracing-1",
        name: "BC Racing BR Series Custom Coilovers",
        category: "Suspension & Bearings",
        subcategory: "Suspension Bushes",
        price: "KES 145,000",
        image: "assets/images/products/suspension-steering/suspension-1.webp",
        description: "30 levels of damping adjustment with full-length ride height adjustability.",
        make: "UNIVERSAL",
        model: "All Performance",
        rating: 4.9
    },
    {
        id: "suspension-ohlins-1",
        name: "Ohlins Gold Series Performance Shock Absorber",
        category: "Suspension & Bearings",
        subcategory: "Shock Absorbers",
        price: "KES 48,000",
        image: "assets/images/products/suspension-steering/suspension-3.webp",
        description: "World-class suspension technology offering unmatched dampening control and ride quality.",
        make: "UNIVERSAL",
        model: "Universal",
        rating: 5.0
    },
    {
        id: "body-spoiler-1",
        name: "Performance Carbon Fiber Rear Spoiler",
        category: "Body Parts",
        subcategory: "Spoilers",
        image: "assets/images/products/body-parts/spoiler-1.png",
        description: "Ultra-lightweight aerodynamic carbon fiber spoiler for enhanced stability.",
        make: "BMW",
        model: "M3",
        year: "2023",
        rating: 4.9
    },
    {
        id: "body-spoiler-2",
        name: "Gloss Black Sport Wing",
        category: "Body Parts",
        subcategory: "Spoilers",
        image: "assets/images/products/body-parts/spoiler-2.png",
        description: "Elegant gloss black finish wing spoiler for a sporty appearance.",
        make: "MERCEDES",
        model: "CLA",
        year: "2024",
        rating: 4.7
    },
    {
        id: "body-steering-rack-1",
        name: "OEM Power Steering Rack Assembly",
        category: "Body Parts",
        subcategory: "Steering racks",
        image: "assets/images/products/body-parts/steering-rack-1.png",
        description: "Precision-engineered power steering rack for smooth handling.",
        make: "TOYOTA",
        model: "Land Cruiser",
        year: "2022",
        rating: 4.8
    },
    {
        id: "body-steering-rack-2",
        name: "Heavy Duty SUV Steering Rack",
        category: "Body Parts",
        subcategory: "Steering racks",
        image: "assets/images/products/body-parts/steering-rack-2.png",
        description: "Reinforced steering rack designed for off-road and heavy-duty use.",
        make: "FORD",
        model: "Ranger",
        year: "2023",
        rating: 4.9
    },
    {
        id: "body-steering-wheel-1",
        name: "Luxury Leather Multi-function Steering Wheel",
        category: "Body Parts",
        subcategory: "Steering Wheels",
        image: "assets/images/products/body-parts/steering-wheel-1.png",
        description: "Premium leather steering wheel with integrated controls.",
        make: "AUDI",
        model: "A6",
        year: "2023",
        rating: 5.0
    },
    {
        id: "body-steering-wheel-2",
        name: "Sport Alcantara Carbon Steering Wheel",
        category: "Body Parts",
        subcategory: "Steering Wheels",
        image: "assets/images/products/body-parts/steering-wheel-2.png",
        description: "Race-inspired steering wheel with Alcantara grips and carbon fiber trim.",
        make: "BMW",
        model: "M5",
        year: "2024",
        rating: 5.0
    },
    {
        id: "body-stone-guard-1",
        name: "Front Bumper Lower Stone Guard",
        category: "Body Parts",
        subcategory: "Stone Guards",
        image: "assets/images/products/body-parts/stone-guard-1.png",
        description: "Durable protective guard against road debris and stones.",
        make: "TOYOTA",
        model: "Hilux",
        year: "2023",
        rating: 4.6
    },
    {
        id: "body-stone-guard-2",
        name: "Heavy Duty Mud Flap Stone Guards",
        category: "Body Parts",
        subcategory: "Stone Guards",
        image: "assets/images/products/body-parts/stone-guard-2.png",
        description: "Set of 4 rugged mud flaps for maximum body protection.",
        make: "MITSUBISHI",
        model: "Pajero",
        year: "2022",
        rating: 4.8
    },
    {
        id: "acc-android-radio-1",
        name: "10-inch Android Multimedia System",
        category: "Car Accessories",
        subcategory: "Android Radios",
        image: "assets/images/products/accessories/android-radio-1.png",
        description: "High-resolution Android touchscreen with GPS navigation, Bluetooth, and Apple CarPlay.",
        make: "UNIVERSAL",
        model: "Multiple",
        year: "2024",
        rating: 4.8
    },
    {
        id: "acc-android-radio-2",
        name: "12-inch Vertical Screen SUV Radio",
        category: "Car Accessories",
        subcategory: "Android Radios",
        image: "assets/images/products/accessories/android-radio-2.png",
        description: "Tesla-style vertical Android screen designed for modern SUV dashboards.",
        make: "UNIVERSAL",
        model: "SUV/Truck",
        year: "2024",
        rating: 4.9
    },
    {
        id: "acc-dashcam-1",
        name: "Dual 4K HDR Dashcam System",
        category: "Car Accessories",
        subcategory: "Dashcams",
        image: "assets/images/products/accessories/dashcam-1.png",
        description: "Crystal clear front and rear recording with night vision and G-sensor.",
        make: "UNIVERSAL",
        model: "Multiple",
        year: "2023",
        rating: 4.7
    },
    {
        id: "acc-dashcam-2",
        name: "Mirror-Style Touchscreen Dashcam",
        category: "Car Accessories",
        subcategory: "Dashcams",
        image: "assets/images/products/accessories/dashcam-2.png",
        description: "Integrates directly into your rearview mirror with a full HD touchscreen display.",
        make: "UNIVERSAL",
        model: "Multiple",
        year: "2023",
        rating: 4.8
    },
    {
        id: "acc-floor-mats-1",
        name: "Custom 5D Diamond Stitch Floor Mats",
        category: "Car Accessories",
        subcategory: "Floor Mats",
        image: "assets/images/products/accessories/floor-mats-1.png",
        description: "Premium synthetic leather floor mats with luxury diamond stitching.",
        make: "UNIVERSAL",
        model: "Multiple",
        year: "2024",
        rating: 5.0
    },
    {
        id: "acc-floor-mats-2",
        name: "Heavy Duty All-Weather Rubber Mats",
        category: "Car Accessories",
        subcategory: "Floor Mats",
        image: "assets/images/products/accessories/floor-mats-2.png",
        description: "Durable deep-dish rubber mats for maximum interior floor protection.",
        make: "UNIVERSAL",
        model: "Multiple",
        year: "2023",
        rating: 4.6
    },
    {
        id: "acc-body-kit-1",
        name: "Full Wide-Body Aero Kit",
        category: "Car Accessories",
        subcategory: "Body Parts",
        image: "assets/images/products/accessories/body-kit-1.png",
        description: "Complete wide-body conversion kit with front bumper, rear diffuser, and side skirts.",
        make: "UNIVERSAL",
        model: "Sport Sedan",
        year: "2024",
        rating: 4.9
    },
    {
        id: "acc-body-kit-2",
        name: "Bumper Extension Styling Kit",
        category: "Car Accessories",
        subcategory: "Body Parts",
        image: "assets/images/products/accessories/body-kit-2.png",
        description: "Elegant bumper extensions and lip spoilers for a subtle yet aggressive look.",
        make: "UNIVERSAL",
        model: "Multiple",
        year: "2023",
        rating: 4.7
    },
    {
        id: "acc-car-alarm-1",
        name: "2-Way LCD Security System",
        category: "Car Accessories",
        subcategory: "Car Alarms",
        image: "assets/images/products/accessories/car-alarm-1.png",
        description: "Advanced 2-way alarm system with LCD remote pager and long-range connectivity.",
        make: "UNIVERSAL",
        model: "Multiple",
        year: "2024",
        rating: 4.8
    },
    {
        id: "acc-car-cover-1",
        name: "Premium Multi-Layer Outdoor Car Cover",
        category: "Car Accessories",
        subcategory: "Car Accessories",
        image: "assets/images/products/accessories/car-cover-1.png",
        description: "Heavy-duty 5-layer waterproof and UV-resistant outdoor car cover.",
        make: "UNIVERSAL",
        model: "Multiple",
        year: "2023",
        rating: 4.8
    },
    {
        id: "acc-car-cover-2",
        name: "Custom Fit Breathable Indoor Cover",
        category: "Car Accessories",
        subcategory: "Car Accessories",
        image: "assets/images/products/accessories/car-cover-2.png",
        description: "Soft, breathable indoor cover to protect from dust and minor scratches.",
        make: "UNIVERSAL",
        model: "Multiple",
        year: "2024",
        rating: 4.9
    },
    {
        id: "acc-gps-tracker-1",
        name: "4G LTE Real-Time GPS Tracker",
        category: "Car Accessories",
        subcategory: "Car Accessories",
        image: "assets/images/products/accessories/gps-tracker-1.png",
        description: "Global tracking with mobile app alerts, geo-fencing, and history playback.",
        make: "UNIVERSAL",
        model: "Multiple",
        year: "2024",
        rating: 4.8
    },
    {
        id: "acc-gps-tracker-2",
        name: "Stealth OBD-II GPS Tracker",
        category: "Car Accessories",
        subcategory: "Car Accessories",
        image: "assets/images/products/accessories/gps-tracker-2.png",
        description: "Compact plug-and-play GPS tracker that installs into the OBD-II port.",
        make: "UNIVERSAL",
        model: "Multiple",
        year: "2023",
        rating: 4.7
    },
    {
        id: "acc-jump-starter-1",
        name: "2000A Peak Portable Jump Starter",
        category: "Car Accessories",
        subcategory: "Car Accessories",
        image: "assets/images/products/accessories/jump-starter-1.png",
        description: "Powerful jump starter power bank for up to 8.0L gas and 6.0L diesel engines.",
        make: "UNIVERSAL",
        model: "Multiple",
        year: "2024",
        rating: 5.0
    },
    {
        id: "acc-jump-starter-2",
        name: "Heavy-Duty 4AWG Jumper Cables",
        category: "Car Accessories",
        subcategory: "Car Accessories",
        image: "assets/images/products/accessories/jump-starter-2.png",
        description: "Professional grade heavy-duty booster cables with reinforced clamps.",
        make: "UNIVERSAL",
        model: "Multiple",
        year: "2023",
        rating: 4.6
    },
    {
        id: "acc-polish-1",
        name: "Ceramic Coating Polish Spray",
        category: "Car Accessories",
        subcategory: "Car Accessories",
        image: "assets/images/products/accessories/polish-1.png",
        description: "Advanced hydrophobic ceramic spray for long-lasting shine and protection.",
        make: "UNIVERSAL",
        model: "Multiple",
        year: "2024",
        rating: 4.8
    },
    {
        id: "acc-polish-2",
        name: "Interior Detailer & UV Protectant",
        category: "Car Accessories",
        subcategory: "Car Accessories",
        image: "assets/images/products/accessories/polish-2.png",
        description: "Cleans and protects interior surfaces while restoring a factory finish.",
        make: "UNIVERSAL",
        model: "Multiple",
        year: "2023",
        rating: 4.7
    },
    {
        id: "acc-speakers-1",
        name: "Premium 6.5-inch 3-Way Component Speakers",
        category: "Car Accessories",
        subcategory: "Car Accessories",
        image: "assets/images/products/accessories/speakers-1.png",
        description: "High-fidelity door speakers with external crossovers and silk dome tweeters.",
        make: "UNIVERSAL",
        model: "Multiple",
        year: "2024",
        rating: 4.9
    },
    {
        id: "acc-speakers-2",
        name: "6x9-inch 4-Way Coaxial Rear Speakers",
        category: "Car Accessories",
        subcategory: "Car Accessories",
        image: "assets/images/products/accessories/speakers-2.png",
        description: "Powerful rear parcel shelf speakers for deep bass and clear highs.",
        make: "UNIVERSAL",
        model: "Multiple",
        year: "2023",
        rating: 4.7
    },
    {
        id: "acc-subwoofer-1",
        name: "Active 8-inch Underseat Compact Subwoofer",
        category: "Car Accessories",
        subcategory: "Car Accessories",
        image: "assets/images/products/accessories/subwoofer-1.png",
        description: "Space-saving powered subwoofer that fits under the front seat for punchy bass.",
        make: "UNIVERSAL",
        model: "Multiple",
        year: "2024",
        rating: 4.8
    },
    {
        id: "acc-subwoofer-2",
        name: "Dual 12-inch Ported Subwoofer Enclosure",
        category: "Car Accessories",
        subcategory: "Car Accessories",
        image: "assets/images/products/accessories/subwoofer-2.png",
        description: "High-output subwoofer box for maximum bass levels in larger vehicles.",
        make: "UNIVERSAL",
        model: "Multiple",
        year: "2023",
        rating: 4.9
    },
    {
        id: "acc-amplifier-1",
        name: "4-Channel Professional Series Amp",
        category: "Car Accessories",
        subcategory: "Car Accessories",
        image: "assets/images/products/accessories/amplifier-1.png",
        description: "High-performance multi-channel amplifier for powering speakers and subwoofers.",
        make: "UNIVERSAL",
        model: "Multiple",
        year: "2024",
        rating: 4.8
    },
    {
        id: "acc-amplifier-2",
        name: "Monoblock Digital Bass Amplifier",
        category: "Car Accessories",
        subcategory: "Car Accessories",
        image: "assets/images/products/accessories/amplifier-2.png",
        description: "Dedicated high-efficiency digital amp for driving large subwoofers.",
        make: "UNIVERSAL",
        model: "Multiple",
        year: "2023",
        rating: 4.7
    },
    {
        id: "acc-stereo-1",
        name: "Bluetooth Single-DIN Smartphone Receiver",
        category: "Car Accessories",
        subcategory: "Car Accessories",
        image: "assets/images/products/accessories/stereo-1.png",
        description: "Modern car stereo with Bluetooth, USB, and hands-free calling support.",
        make: "UNIVERSAL",
        model: "Multiple",
        year: "2024",
        rating: 4.6
    },
    {
        id: "acc-stereo-2",
        name: "Double-DIN 7-inch Touchscreen Receiver",
        category: "Car Accessories",
        subcategory: "Car Accessories",
        image: "assets/images/products/accessories/stereo-2.png",
        description: "Touchscreen head unit with Android Auto, Apple CarPlay, and rear camera support.",
        make: "UNIVERSAL",
        model: "Multiple",
        year: "2024",
        rating: 4.8
    },
    {
        id: "acc-shark-fin-1",
        name: "Gloss Black Shark Fin Aerial",
        category: "Car Accessories",
        subcategory: "Car Accessories",
        image: "assets/images/products/accessories/shark-fin-1.png",
        description: "Aerodynamic shark fin antenna with integrated signal booster and gloss black finish.",
        make: "UNIVERSAL",
        model: "Multiple",
        year: "2024",
        rating: 4.8
    },
    {
        id: "acc-steering-wrap-1",
        name: "Luxury Alcantara Steering Wheel Wrap",
        category: "Car Accessories",
        subcategory: "Steering Covers",
        price: "KES 6,500",
        image: "assets/images/products/exterior-accessories/acc-3.webp",
        description: "Hand-stitched premium Alcantara wrap for ultimate grip and interior luxury.",
        make: "UNIVERSAL",
        model: "Universal",
        rating: 4.9
    }
];
